[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/__/auth/*"
  to = "https://isnine-1dd6c.firebaseapp.com/__/auth/:splat"
  status = 200
  force = true